variable "ami" {}
variable "instance_type" {}
variable "private_az" {}
variable "private_key" {}
variable "sg" {}
variable "public_subnet" {}
variable "public_az" {}
variable "key_name" {}
variable "public_key_path" {}